### PR TITLE
Add Builder's Refuge

### PR DESCRIPTION
**Pull request by Windos-7**
## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by strich3** [comment]
It looks good, but the images seem weird**https://raw.githubusercontent.com/LabyMod/server-media/b193d295cdb2c00e1808cfcba742b0d1a4aaa689/minecraft_servers/buildersrefuge/background.png**

**Comment by Windos-7** [comment]
I used an AI upscaler on this image used on the website (https://www.buildersrefuge.com/wp-content/uploads/2018/11/blockworks.png) so that it can fit the resolution for the background image, so thats why it looks a bit off
I can try taking a new screenshot from the server if you want

**Comment by strich3** [comment]
> I used an AI upscaler on this image used on the website (https://www.buildersrefuge.com/wp-content/uploads/2018/11/blockworks.png) so that it can fit the resolution for the background image, so thats why it looks a bit off
> I can try taking a new screenshot from the server if you want

I guess it would be better to take a new picture. Because it‘s all white and looks just a bit weird

**Comment by strich3** [comment]
I mean it‘s 90% white. Without any colors

**Comment by strich3** [comment]
This looks much better now. :)

**Pull request merged**
