### PR TITLE
Request for BlockLeben

### PR DESCRIPTION
**Pull request by Jxelsw**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by maaaathis — CHANGES_REQUESTED** [review]
You commited your `.vs` settings and temp data.

**Comment by Jxelsw** [comment]
OK, I FIX IT!

**Comment by Jxelsw** [comment]
I FIXED IT

**Review by maaaathis — CHANGES_REQUESTED** [review]

**Comment by Jxelsw** [comment]
jetzt aber xD

**Review by DoJapHD — APPROVED** [review]

**Pull request merged**
