### PR TITLE
Add FlynnLG.de

### PR DESCRIPTION
**Pull request by FlynnLG**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
We (FlynnLG.de) are currently in maintenance.

### CODE REVIEW

**Review by JakobBruening — APPROVED** [review]
Thank you!

**Review by JakobBruening — CHANGES_REQUESTED** [review]
Yup, the workflow found a mistake:

Error: Invalid background size! Size is 2560x1440px, must be 1280x720px: minecraft_servers/flynnlg/background.png
Error: Invalid hDPI background size! Size is 3840x2160px, must be 1920x1080px: minecraft_servers/flynnlg/background@2x.png

😬✌

**Comment by FlynnLG** [comment]
I feel uncomfortable now, because I checked it before more than 3 times. But i will fix it, sorry for that!

**Comment by FlynnLG** [comment]
So, changed. But cannot add them, do I have to create a new pull request?

**Comment by JakobBruening** [comment]
Oh, yes, I've already merged the pull request now - Feel free to create a new one, yes! 😅

**Comment by FlynnLG** [comment]
Okay, no problem. I've created a new pull request one.

**Pull request merged**
