### PR TITLE
Add Craftplay

### PR DESCRIPTION
**Pull request by PanetiX**
## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments
Sorry for that many commits i forgot to compress the image files at first.

### CODE REVIEW

**Comment by strich3** [comment]
you won't need the banner.png

**Comment by PanetiX** [comment]
> you won't need the banner.png

its for a labymod 4 feature (ingame serverlist) :)

**Comment by niklaswa** [comment]
> > you won't need the banner.png
> 
> its for a labymod 4 feature (ingame serverlist) :)

The banner is actually displayed above the tab list

**Comment by strich3** [comment]
> > > you won't need the banner.png
> > 
> > 
> > its for a labymod 4 feature (ingame serverlist) :)
> 
> The banner is actually displayed above the tab list

Isn't that a api thing?

**Review by JakobBruening — CHANGES_REQUESTED** [review]

**Pull request merged**
