### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by MELONEODERSO**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by DoJapHD** [comment]
Server is not reachable as mentioned several times before.

**Comment by MELONEODERSO** [comment]
The server is online all the time, what do I have to change so that this message does not appear?

**Review by DoJapHD — COMMENTED** [review]
API only bugged, please excuse me for that.

**Comment by MELONEODERSO** [comment]
Should I make a new pull request?

**Pull request closed without merging**
