### PR TITLE
Edit Manifest.json

### PR DESCRIPTION
**Pull request by quele-official**
## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by JakobBruening — APPROVED** [review]
Thank you! Could you resolve the conficts, so I can merge?

**Comment by JakobBruening** [comment]
Can you resolve the conflicts, so I can merge the changes @quele-official? ✌

**Comment by quele-official** [comment]
I hope the conflicts have been successfully resolved, have now also added some data.

**Review by JakobBruening — APPROVED** [review]
Looks good now - Thank you!

**Pull request merged**
