### PR TITLE
hypemania

### PR DESCRIPTION
**Pull request by NevioDev**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by JakobBruening — CHANGES_REQUESTED** [review]
- Please compress your images
Additionally, we recommend using a transparent icon.

**Comment by NevioDev** [comment]
I dont understand why I dont can add the web URL an the web_support

**Comment by NevioDev** [comment]
i dont see what i do wrong

**Review by NevioDev — COMMENTED** [review]
remove /

**Review by Hypemania-Network — COMMENTED** [review]
I think now its work

**Comment by NevioDev** [comment]
Is sth. wrong? @JakobBruening

**Pull request closed without merging**
