### PR TITLE
Add server MineHub.cz

### PR DESCRIPTION
**Pull request by Foxxy889**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by JakobBruening — APPROVED** [review]
Hey!

Thank you for your contribution!
Could you make the background of the icon transparent so that it looks better on our pages?

**Comment by Foxxy889** [comment]
Hello,

thanks, I changed the files accordingly. I think it would be better if there was information about what are `icon.png` and `logo.png` images exactly for.

**Comment by JakobBruening** [comment]
We have already mentioned a few points in the README-file.
But yes, I'll add more examples very soon! 
If you have ideas or wished, feel free to create a Pull request!
Thank you!

**Comment by JakobBruening** [comment]
@Foxxy889 Just FYI; I've added [more examples related to LABY.net](https://github.com/LabyMod/server-media/commit/d7e9afce7c4e4c04f13190bcdfecf0538f1a7c70) 🌟

**Comment by Foxxy889** [comment]
Thanks!

**Pull request merged**
