### PR TITLE
Changed Images from OpInsel

### PR DESCRIPTION
**Pull request by Nils-afk**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by Nils-afk** [comment]
What can i do to fix this?

**Comment by Nils-afk** [comment]
fixed

**Review by maaaathis — COMMENTED** [review]
Is the Server online?
image

**Comment by Nils-afk** [comment]
Yes, the server is online
image
We are only doing maintenance work at the moment. Should be back in 3 days at the latest.

**Comment by Nils-afk** [comment]
image
I forgot to change the text. But it's back to normal now.

**Comment by Nils-afk** [comment]
image
Here is proof that the servers are online

**Comment by Nils-afk** [comment]
@maaaathis

**Comment by DoJapHD** [comment]
Server has to be **publicly** available (aka. released).

**Comment by Nils-afk** [comment]
Ok, done

**Comment by Nils-afk** [comment]
I have just finished the maintenance work early.

**Pull request closed without merging**
