### PR TITLE
Update Lostify gamemodes, remove ts & web_support and update discord.rename_to_minecraft_name

### PR DESCRIPTION
**Pull request by maaaathis**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

Update Lostify manifest: 

- Remove Teamspeak
- Remove AmongUs gamemode
- Remove CityBuild Gamemode
- Bump CityBuildFuture & McDurchspielen to mc v1.20.2
- Update Discord invite url regarding to https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md?plain=1#L65-L67
- Remove web_support
- Set discord.rename_to_minecraft_name to false regarding to https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md?plain=1#L27

### CODE REVIEW

**Comment by maaaathis** [comment]
Any Update @DoJapHD ?

**Review by DoJapHD — CHANGES_REQUESTED** [review]
Server offline, Support can't be forum; discord can't be custom domain (has to be https://discord.gg/[INVITE]), Discord rename_to_minecraft_name has to be "false"

**Comment by maaaathis** [comment]
> Server offline, Support can't be forum; discord can't be custom domain (has to be [https://discord.gg/[INVITE]](https://discord.gg/%5BINVITE%5D)), Discord rename_to_minecraft_name has to be "false"

But that's are the current data. I changed nothing regarding these points. I only updated the game modes & removed the Teamspeak.
And the Server isn't offline - the Firewall sometimes blocks all connections through any kind of datacenter.

**Comment by maaaathis** [comment]
The Discord got approved here https://github.com/LabyMod/server-media/pull/413

The forum & discord renaming got approved here https://github.com/LabyMod/server-media/pull/141

**Comment by DoJapHD** [comment]
I got the instructions to make sure that these features are only being used by LabyMod partners.
As the answer to my question to the partner management whether your server is a partner was no, you cannot use these features and they'll need to be changed.

**Comment by maaaathis** [comment]
Okay. For my part, even though I haven't changed anything with the Discord link, I've adjusted it^^

**Comment by DoJapHD** [comment]
All the other things have to be changed, too.
Otherwise I won't accept the PR.

**Comment by maaaathis** [comment]
> All the other things have to be changed, too. Otherwise I won't accept the PR.

The documentation doesn't contains anything about these points. 

See https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md?plain=1#L16 & https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md?plain=1#L27

Why has `discord.rename_to_minecraft_name` to be `false`? The documentation contains nothing about this. Any why is a forum based website no valid way to get support, but a faq page?

Where is your reference? According to the docs, my manifest is valid and contains no partners only content.

**Comment by JakobBruening** [comment]
Hey @maaaathis!

I don't really understand the problem right now. We ask you to make changes that are not major. Where exactly is the problem? 
You are more than welcome to submit a PR to update the docs. Thats one reason why open source is beatutiful - next time you can make sure that the next person has no misunderstandings by yourself! :)


Regarding your issues:
1. `discord.rename_to_minecraft_name`:
Sorry, but I honestly don't understand your problem here. There is no reason for you to set this to `true`, as the feature is only enabled for partners. To keep everything consistent, we have decided to only allow this value to be set to `true` in partner configurations. Simple reason. A small change for you and we're happy. I don't know why there has to be a discussion about it. [But I have of course taken your advice regarding the documentation on board](https://github.com/LabyMod/server-media/commit/9a7ee5d08d8fd29f72844931b5e56987b48f6fa1), thank you.

2. Your support page
I have not included anything in the documentation here. For one simple reason: we do not prohibit anything directly. We accept suitable support pages. However, we are careful with forums, as they are not always pure support platforms and many servers use them as advertising platforms or websites. If there is a page in forums that explicitly describes "How-To-Get Support" or has an FAQ, we will of course allow this.
Again, I don't understand why there is any basis for discussion. Let's imagine an example. Imagine you are a user and want support from your server. Then you click on the support link at laby.net and are taken to an empty forum page. Does that help you as a user? Probably not. That's why @DoJapHD is absolutely right. If this page has always existed like this when I merged the PR, it was a mistake of mine to merge it. So: Please change it.

Last but not least:
Mistakes can simply happen during the review. I admit that this shouldn't happen and that too many mistakes have been made here. But that's no reason for these mistakes to go through again in the next PR. If you notice errors/mistakes yourself that you can fix: Feel free to submit a PR or jusr report it in an issue/PR friendly. It's very simple.

And it stays that the same. Please fix the two issues, then we'll merge the pull request.
If you have any other questions on that, feel free to comment again and I will be happy to anwer.

Have a nice evening!
BR, Jakob

**Comment by maaaathis** [comment]
Hello @JakobBruening.

Thanks for the clarification.

Maybe I'm a bit handicapped by my work, but this PR is solely to remove old outdated gamemodes & teamspeak. That's the only reason for this PR.
The classic PR review usually only reviews the changes made and not the entire manifest. That's the reason for my little discussion here, because I didn't change anything in those three items, so I don't see the need for a change in this PR. Normally, I would make an issue after this PR to address your criticisms and resolve them myself if no one else does.

Statements like "`rename_to_minecraft_name` have to be `false`" are non-transparent and refer to an undocumented rule. Thanks for updating the docs, otherwise I would have done it after this PR.

I understand your approach to the web support pages, but unfortunately I find it neither transparent nor understandable. But user convenience is of course the top priority - I'm completely with you on that. I have of course removed the web_support item. The forum hasn't existed for too long anyway, which is why I would have removed this item sooner or later anyway. 

I apologize very much for all this trouble and confusion here and have adjusted the relevant points in my PR.

Best wishes
Mathis

**Comment by JakobBruening** [comment]
Hey @maaaathis!
Thank you for the comment. We are happy to take your feedback on board again. If you have any ideas for making processes more transparent here, feel free to create an issue or a PR!

BR, Jakob

**Review by JakobBruening — APPROVED** [review]

**Pull request merged**
