### PR TITLE
Add LazerLife

### PR DESCRIPTION
**Pull request by Mik6060**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by scrummer** [comment]
Hi @Mik6060 
Can you please check your server? I was not able to connect to it neither with 1.8 nor with 1.19.

We can only accept servers which are up and running and available for publicity

Best,
Scrummer

**Comment by Mik6060** [comment]
Hello @scrummer 
Everything should work now, the server is running on version 1.19.2 or higher

**Comment by scrummer** [comment]
@Mik6060 Still not able to connect:
image
```
could not connect to a default or fallback server. incorrectly configured address/port/firewall? io.netty.channel.AbstractChannel$AnnotatedConnectException
```

Seems to be a server-side problem from googling it quickly...

**Comment by Mik6060** [comment]
Which version are you trying to connect to?

**Comment by Mik6060** [comment]
Hello @scrummer 
It should actually work now it may be that where you tried to connect I just did something on the server but now it has to work. With version 1.19.2 or higher. I have no problems connecting and neither does my second account.

**Review by scrummer — CHANGES_REQUESTED** [review]
Now it works and I can connect.
One more small thing (sorry, did not see that in the first review): Please compress your images. They're too large.

~Scrummer

**Comment by Mik6060** [comment]
ok i did it

**Review by scrummer — APPROVED** [review]

**Comment by scrummer** [comment]
Thank you!

**Pull request merged**
