### PR TITLE
minepulla

### PR DESCRIPTION
**Pull request by nickynice1**
Added  new Logo/Icon LabyMod/server-media#838

### CODE REVIEW

**Comment by DoJapHD** [comment]
Are you sure that you did the right thing?
You deleted everything but your comment states "adding new logo/icon".

**Comment by nickynice1** [comment]
No that’s not the right thing. I pushed via GitHub desktop the new logo and
icon, where the format is better. I only want to change it.

Now everything is deleted?


DoJapHD ***@***.***> schrieb am Sa. 9. Dez. 2023 um 22:02:

**Comment by DoJapHD** [comment]
Yes, your folder is deleted.
Just search for it in your fork. You'll see that you won't find it.

https://i.imgur.com/MbsHSuv.png

**Comment by nickynice1** [comment]
Perfect…

I will reupload tonight and make a pull request…

DoJapHD ***@***.***> schrieb am So. 10. Dez. 2023 um 13:29:

**Comment by nickynice1** [comment]
hey dojap

In my case see the directory. How I can only change the logo and icon ?

*Mit freundlichen Grüßen/Best regards*

*minepulla - Team*

🌍 minepulla.net - 📨 ***@***.*** -  📞 discord.minepulla.net
***@***.***>




Am So., 10. Dez. 2023 um 13:30 Uhr schrieb Niklas Bergmann <
***@***.***>:

**Comment by DoJapHD** [comment]
Did you really commit and push your changes to your fork?

**Comment by nickynice1** [comment]
Yes, I did.
*Mit freundlichen Grüßen/Best regards*

*minepulla - Team*

🌍 minepulla.net - 📨 ***@***.*** -  📞 discord.minepulla.net
***@***.***>




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Di., 12. Dez. 2023 um 10:11 Uhr schrieb DoJapHD ***@***.***

**Comment by DoJapHD** [comment]
Well, doesn't seem like it.
As mentioned, the folder is non-existent in your fork.

Please try again and commit/push it to your fork.

**Comment by nickynice1** [comment]
ok i did.

**Comment by DoJapHD** [comment]
You'll probably need to do another pull request.
I'll close this one, please open a new PR with your fork.

**Pull request closed without merging**
