### PR TITLE
Adding SWHub.net

### PR DESCRIPTION
**Pull request by MatthiasLettner**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by maaaathis** [comment]
You don't need to open a new PR on such a change. The old PR updates automatically

**Comment by MatthiasLettner** [comment]
so just edit the file on my repo?

**Comment by maaaathis** [comment]
> so just edit the file on my repo?

yeah, as long as you commit to the same branch

**Comment by MatthiasLettner** [comment]
ah ok thx <3

**Comment by MatthiasLettner** [comment]
yeah finally xD

**Comment by maaaathis** [comment]
> do i need to change something now? because at the top it says
> 
> ```
> Please remove / at the end of url (social.web_shop)
> ```
> 
> Please fix the issues by pushing one commit to the pull request to prevent too many automatic reviews.
> 
> I removed it already

No, you're good to go

the latest checks passed:
image

**Comment by maaaathis** [comment]
> nice - do i need then now to do something by my own?

As long as @DoJapHD has no more points, no

**Comment by DoJapHD** [comment]
Server is in maintenance mode
Open another PR once server is publicly available

**Pull request closed without merging**
