### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by r9x**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by r9x** [comment]
.

**Comment by r9x** [comment]
> Please compress images

done

**Comment by scrummer** [comment]
@r9x With your image-compressing update you deleted your whole folder including the `manifest.json` which is mandatory. Please create it again.

And another thing: Although it is not a requirement, please rename your folder to all lowercase `VeinMC -> veinmc` to match the convention from all other servers. Make sure to adapt this change to your manifest.json

**Comment by r9x** [comment]
@scrummer

**Review by JakobBruening — APPROVED** [review]

**Pull request merged**
