### PR TITLE
Add Gazami

### PR DESCRIPTION
**Pull request by SpiddlTV**
## Type of change

- [x] Add new directory for a server

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by SpiddlTV** [comment]
background@2x
icon
logo
[manifest.json](https://github.com/LabyMod/server-media/files/13953030/manifest.json)
icon@2x
logo@2x
background

**Comment by SpiddlTV** [comment]
background
icon
logo

**Review by SpiddlTV — COMMENTED** [review]
### New Images and Manifest
[manifest.json](https://github.com/LabyMod/server-media/files/13953092/manifest.json)
background
icon
logo

**Comment by maaaathis** [comment]
You need to commit your files to your branch.

**Review by SpiddlTV — COMMENTED** [review]
icon
background

**Pull request closed without merging**
