### PR TITLE
Update manifest.json and icons/logos

### PR DESCRIPTION
**Pull request by Craftportal**
icon
icon@2x
logo
icon@2x
## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [x] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by maaaathis** [comment]
You need to replace the image files inside your server directory and commit that to change your images.

**Comment by Craftportal** [comment]
**Uploads are disabled.**
File uploads require push access to this repository.

?

**Comment by maaaathis** [comment]
> **Uploads are disabled.** File uploads require push access to this repository.
> 
> ?

In your own fork obviously: https://github.com/Craftportal/server-media/tree/patch-7/minecraft_servers/craftportal

**Comment by Craftportal** [comment]
Okay thank you

**Comment by maaaathis** [comment]
You don't need to close the PR an reopen it. It updates automatically as long as you push a commit to your origin branch.

**Pull request closed without merging**
