### PR TITLE
Fix Quercon #2

### PR DESCRIPTION
**Pull request by S4MON1X**
## Type of change

- [x] Update directory of a server

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
Added domain wildcard.

### CODE REVIEW

**Review by JakobBruening — COMMENTED** [review]
image

Does not work for me.

**Comment by JakobBruening** [comment]
In general, the server is not online currently (and will therefore not be displayed on LABY.net). Is this a bug?

**Comment by S4MON1X** [comment]
The server adress is mc.quercon.eu

**Comment by S4MON1X** [comment]
So I looked up and laby is not working cause of DNS error

**Comment by JakobBruening** [comment]
But the server is generally not working atm 😅

**Comment by S4MON1X** [comment]
Wait a minute, I`m fixing error in DNS. The server will be online in few minutes.

**Comment by S4MON1X** [comment]
Sorry for the inconvenience

**Comment by JakobBruening** [comment]
All good! But it is still not working:

**quercon.eu**


**mc.quercon.eu**

**Comment by S4MON1X** [comment]
It looks like automatic maintenance has started. Sorry, but this situation is unexpected. I will mention you when we fix the error.

**Comment by S4MON1X** [comment]
@JakobBruening Issue fixed, join through mc.quercon.eu and when you join type /register yourpass yourpass

**Comment by JakobBruening** [comment]
Okay - Another quesion: Is the server a premium server? Because I cannot see my cosmetics there.

**Comment by S4MON1X** [comment]
No, it isnt, but the labyapi is implemented. So I don't know why it don't shown up.

**Comment by S4MON1X** [comment]
The premium login system probably dont work.

**Comment by JakobBruening** [comment]
I have just tested it: The server is definitely not a premium server. Since we only support premium servers (everywhere), we unfortunately do not merge such pull requests. Since the server was not online the first time, this was not directly apparent to us. So we would remove the data, also the data which is currently already merged 😬

Of course we would be happy to see another pull request from the server at some point - but it has to be premium-only!

Best regards
Jakob ✌

**Pull request closed without merging**
