### PR TITLE
fixed manifest.json added background@2x.png

### PR DESCRIPTION
**Pull request by FrinshHD**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by FrinshHD** [comment]
What is wrong?

**Comment by JakobBruening** [comment]
Merge conflicts:
minecraft_servers/anturnia/background.png
minecraft_servers/anturnia/manifest.json

**Comment by FrinshHD** [comment]
How can i fix that?

**Comment by FrinshHD** [comment]
Cause I want to replace them @JakobBruening

**Comment by JakobBruening** [comment]
We took the easiest way - I've removed the server from the repository, so it is added new with the PR.

**Review by JakobBruening — CHANGES_REQUESTED** [review]
Please compress the images (especially the `background@2x.png`)

**Comment by FrinshHD** [comment]
did it

**Review by JakobBruening — APPROVED** [review]
Thank you!

**Pull request merged**
