### PR TITLE
Overwrite StyyCraft.net images

### PR DESCRIPTION
**Pull request by RappyTV**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
I am not in charge of the server nor in any way related. The server owner asked me to open this pull request for him because he is not experienced with GitHub:
image

### CODE REVIEW

**Review by maaaathis — CHANGES_REQUESTED** [review]
Compress your background.png

**Comment by noahtrxMC** [comment]
> Compress your background.png

The file contains the same size as the old background. So why do we need to compress?

**Comment by maaaathis** [comment]
> * I have compressed the images appropriately (e.g. on https://tinypng.com)

Yeah right, but ~ 1 MB for a 1280x720 pixel background is to big. The reference here is about several hundred KB.
Probably slipped through before.

But see also here: https://github.com/LabyMod/server-media/pull/940#discussion_r1471808657 (here it was previously just under 800 KB, could be compressed to just under 350 KB).
The step for compressing is also in the guideline and even in the PR itself ("[x] I have compressed the images appropriately)"). Just run it through https://tinypng.com/

**Comment by RappyTV** [comment]
alr, I just compressed it, now it's 743KB smaller.

**Review by maaaathis — APPROVED** [review]
looks good 👍

**Review by DoJapHD — APPROVED** [review]

**Pull request merged**
