### PR TITLE
Akratis

### PR DESCRIPTION
**Pull request by basti050295**
## Type of change

- [X] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

- Add New Server

### CODE REVIEW

**Comment by basti050295** [comment]
new server

**Comment by basti050295** [comment]
Is this normal as it always fails?

**Comment by maaaathis** [comment]
> Is this normal as it always fails?

No, your JSON manifest is just not valid:

- JSON is invalid! Workflow is not able to check minecraft_servers/akratis/manifest.json

**Comment by basti050295** [comment]
What exactly is not valid about it? So where did I make the mistake?

BlueMail for Android<https://bluemail.me> herunterladen
Am 22. Aug. 2024, um 05:39, mathis ***@***.******@***.***>> schrieb:

Is this normal as it always fails?

No, your JSON manifest is just not valid:

  *   JSON is invalid! Workflow is not able to check minecraft_servers/akratis/manifest.json

**Review by basti050295 — COMMENTED** [review]
checked my files

**Comment by DoJapHD** [comment]
Server is in maintenance mode;
Reopen PR once server is publicly available

**Comment by basti050295** [comment]
maintenance mode ist offine now

**Pull request closed without merging**
