### PR TITLE
all updatet

### PR DESCRIPTION
**Pull request by Tamino112**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by Tamino112** [comment]
its online

**Comment by Tamino112** [comment]
We'll be publishing soon, there are already beta testers, but I'd like everything to work with labymod before it's real. Please keep an eye on it

**Comment by DoJapHD** [comment]
What exactly is "soon"?

**Comment by Tamino112** [comment]
We want to release in 3 to 4 weeks at the latest

**Comment by Tamino112** [comment]
> What exactly is "soon"?
We want to release in 3 to 4 weeks at the latest

**Comment by DoJapHD** [comment]
Okay
Just open another PR once the server is publicly available

**Comment by Tamino112** [comment]
ok :-(

**Pull request closed without merging**
