### PR TITLE
Adding SWHub.net

### PR DESCRIPTION
**Pull request by MatthiasLettner**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by DoJapHD** [comment]
Not joinable

**Comment by MatthiasLettner** [comment]
now it should work

**Comment by DoJapHD** [comment]
Nope, server is offline

**Comment by MatthiasLettner** [comment]
sorry for the inconvenience, now the server should work

**Review by DoJapHD — APPROVED** [review]

**Pull request merged**
