### PR TITLE
Add Quercon.eu

### PR DESCRIPTION
**Pull request by S4MON1X**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
The server just came from 2 week maintenance so players are returning...

### CODE REVIEW

**Comment by scrummer** [comment]
Thank you!

**Comment by S4MON1X** [comment]
You're welcome. I just want to ask how long it will take to see the information on the page.
´

**Comment by scrummer** [comment]
@S4MON1X It does not take that long. Normally on the same day (or even after a few hours) it is online.

But one question: You have choosen "quercon.eu" as name of the server. I think to prevent compatibility issues, it would be better to rename `server_name` and `nice_name` to `quercon` and `Quercon` - or is your "name" really "Quercon.eu"?

BR 
Scrummer

**Comment by scrummer** [comment]
@S4MON1X Okay, actually I did some researching and the `server_name` MUST be exactly the same as the dirctory name...

I will change it in a separate PR.

**Pull request merged**
