### PR TITLE
OpInsel Update

### PR DESCRIPTION
**Pull request by Nils-afk**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by maaaathis** [comment]
Eygelshoven is still not in Germany 😅

**Comment by Nils-afk** [comment]
Anyway, I brought it to Germany 😂

**Comment by maaaathis** [comment]
> Anyway, I brought it to Germany 😂

Don't forget to update the Wikipedia page: https://en.wikipedia.org/wiki/Eygelshoven

**Comment by Nils-afk** [comment]
Oh yes, I forgot about that, sorry. I think it will take a few weeks to update

**Comment by Nils-afk** [comment]
They are slow

**Comment by Nils-afk** [comment]
My Server Crashed Today. OpInsel will be offline for 2-3h.

**Review by DoJapHD — APPROVED** [review]

**Pull request merged**
