### PR TITLE
Erstelle melonblocks

### PR DESCRIPTION
**Pull request by leAaron**
## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by leAaron** [comment]
background
icon

**Comment by leAaron** [comment]
icon@2x

**Comment by DoJapHD** [comment]
Inactive PR

**Pull request closed without merging**
