### PR TITLE
Update Dyhntastic

### PR DESCRIPTION
**Pull request by Dyhnen**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by JakobBruening — CHANGES_REQUESTED** [review]
Please fix formatting

**Review by Dyhnen — COMMENTED** [review]
what should be changed?

**Comment by JakobBruening** [comment]
Bildschirmfoto 2023-04-30 um 21 33 21

Use the same formatting as in our example. Spaces are wrong here.

**Comment by Dyhnen** [comment]
Screenshot_1

I have uploaded this so that it fits me

**Pull request merged**
