### PR TITLE
@Thundiii

### PR DESCRIPTION
**Pull request by Thundiii**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by JakobBruening** [comment]
The data looks good!
I saw that you are currently still in a closed BETA. The repository aims more at servers that are already released. 
But we would definetily like to have a look at the current version of the server. Is that possible? If you need to send data that is sensitive for this, feel free to write to jakob@labymod.net ✌

**Comment by Thundiii** [comment]
i disabled the whitelist, youre welcome to take a look :D

**Comment by JakobBruening** [comment]
Unfortunately, I cannot join :/

**Comment by Thundiii** [comment]
Should work now, sorry :D

**Review by JakobBruening — APPROVED** [review]
Thank you for your contribution and for the fast anwers! 🌟

**Pull request merged**
