### PR TITLE
Create PixelPulseCraft

### PR DESCRIPTION
**Pull request by elxAl33**
## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [x] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

background
background@2x
icon
icon@2x
[manifest.json](https://github.com/LabyMod/server-media/files/14073180/manifest.json)
Images

### CODE REVIEW

**Comment by maaaathis** [comment]
duplicate of https://github.com/LabyMod/server-media/pull/926

**Comment by maaaathis** [comment]
Empty PR, cause duplicate of #926  - close this PR @elxAl33

**Comment by maaaathis** [comment]
also duplicate of #924

**Comment by elxAl33** [comment]
@maaaathis Hello Mathis, Sorry that i do everything wrong i just dont know how it works i Would appreciate if you help me.

**Pull request closed without merging**
