### PR TITLE
Add Distaria.NET

### PR DESCRIPTION
**Pull request by 1combit**
## Type of change

- [ x ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ x ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ x ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ x ] I have created the manifest.json with the required values

### CODE REVIEW

**Review by scrummer — CHANGES_REQUESTED** [review]
Thank you for your contribution. In general there are a few points I ask you to check again:
- [x] The images are quite large - please check the [image specification](https://github.com/LabyMod/server-media/blob/master/docs/Files.md#image-specification) and compress them properly
- [x] The `icon.png` has not the correct size (check [filestructure](https://github.com/LabyMod/server-media/blob/master/docs/Files.md#filestructure)!)

Tip: The logo/icons should fill the whole artboard (e.g. 256x256px). It will not look that good when you have large free spaces around your logo.

**Comment by 1combit** [comment]
So I adjusted the pictures again. Oh and thanks for the tip but I can not edit the pictures in the direction but I think if it does not look too good I will update it again in the future :D

**Review by scrummer — CHANGES_REQUESTED** [review]
@1combit There are still some things not good:
- [ ] File sizes of `background.png` and `background@2x.png`. Try to use https://compresspng.com/
- [x] The `logo.png` is 128x128 in your case. The required measurements are between `128x256`(min) and `256x512`(max) (--> see [file-structure](https://github.com/LabyMod/server-media/blob/master/docs/Files.md#filestructure) for the exact sizes.

**Comment by 1combit** [comment]
Fixed.

**Review by scrummer — APPROVED** [review]

**Comment by scrummer** [comment]
Thank you!

**Comment by 1combit** [comment]
thy :3

**Pull request merged**
