### PR TITLE
Create pixelpulsecraft

### PR DESCRIPTION
**Pull request by elxAl33**
## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [x] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
background
background@2x
icon
icon@2x
[manifest.json](https://github.com/LabyMod/server-media/files/14073254/manifest.json)

### CODE REVIEW

**Comment by maaaathis** [comment]
Commit the files to your branch

**Comment by maaaathis** [comment]
#924, #925 & 926

**Comment by elxAl33** [comment]
> Commit the files to your branch

How i do it?

**Comment by maaaathis** [comment]
> > Commit the files to your branch
> 
> How i do it?

You did it already in #926

**Comment by elxAl33** [comment]
> > > Commit the files to your branch
> > 
> > 
> > How i do it?
> 
> You did it already in #926

Im confused you maybe got discord so we can type there?

**Comment by maaaathis** [comment]
Why did you close #926, there were only the pictures in the wrong format and uncompressed?

But you can create your server directory here and upload in that directory your files: https://github.com/elxAl33/server-media/tree/patch-3/minecraft_servers.  The PR updates automatically.

**Comment by elxAl33** [comment]
> Why did you close #926, there were only the pictures in the wrong format and uncompressed? Everything else looked good.
> 
> But you can create your server directory here and upload in that directory your files: https://github.com/elxAl33/server-media/tree/patch-3/minecraft_servers. The PR updates automatically and you don't need to create another PR.

So should i close this then now and reopen the other one or what should i do

**Comment by maaaathis** [comment]
> > Why did you close #926, there were only the pictures in the wrong format and uncompressed? Everything else looked good.
> > But you can create your server directory here and upload in that directory your files: https://github.com/elxAl33/server-media/tree/patch-3/minecraft_servers. The PR updates automatically and you don't need to create another PR.
> 
> So should i close this then now and reopen the other one or what should i do

Yes. I think that's the smartest idea. The issues with the images can you see here: https://github.com/LabyMod/server-media/pull/926#issuecomment-1913271616

**Pull request closed without merging**
