### PR TITLE
Request to add Lurexos.net

### PR DESCRIPTION
**Pull request by LPenx**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

I've pack it up into a .zip (down below)
[lurexos.zip](https://github.com/LabyMod/server-media/files/11361881/lurexos.zip)
(with the updated things)

### CODE REVIEW

**Comment by LPenx** [comment]
background@2x

**Comment by LPenx** [comment]
background

**Comment by JakobBruening** [comment]
Something is wrong here. No new directory was added.

**Comment by LPenx** [comment]
> Something is wrong here. No new directory was added.

Whats wrong?

**Comment by JakobBruening** [comment]
There are no new files added.

Bildschirmfoto 2023-04-30 um 21 31 39

**Comment by LPenx** [comment]
> There are no new files added.
> 
> Bildschirmfoto 2023-04-30 um 21 31 39

Hmh, can you tell me what was wrong? Maybe i misapprehended this

**Pull request closed without merging**
