### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by Kallecrafter**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Comment by Kallecrafter** [comment]
json converter tells me that everything is okay. Github is causing problems again and I have no idea what the problem is.

**Comment by Kallecrafter** [comment]
json converter sagt mir das alles okay ist. Github macht wieder Probleme und ich hab null ahnung woran das liegen sollte.

**Comment by Kallecrafter** [comment]
.

**Review by Kallecrafter — COMMENTED** [review]
.

**Review by DoJapHD — APPROVED** [review]

**Pull request merged**
