### PR TITLE
femboymc

### PR DESCRIPTION
**Pull request by ErrorHunter1**
## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by maaaathis — CHANGES_REQUESTED** [review]

**Review by DoJapHD — CHANGES_REQUESTED** [review]

**Comment by DoJapHD** [comment]
Inactive

**Comment by ErrorHunter1** [comment]
Hmm why was it closed?

**Comment by maaaathis** [comment]
> Hmm why was it closed?

You didn't reacted to the comment: https://github.com/LabyMod/server-media/pull/1066#discussion_r1571911583

**Comment by ErrorHunter1** [comment]
I wasn't notified that day otherwise I would have done it the same day

**Pull request closed without merging**
