### PR TITLE
Added the 2x background to LendMark

### PR DESCRIPTION
**Pull request by SlenkyDev**
## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

### CODE REVIEW

**Review by JakobBruening — APPROVED** [review]
👍🏼

**Comment by JakobBruening** [comment]
I have removed your discord url in ff0a904c9a19a3c8e2a71741d34d581419e804fa.
The url is not a discord invite, it's for an application. So, please use the direct discord invite url.

**Comment by SlenkyDev** [comment]
> I have removed your discord url in [ff0a904](https://github.com/LabyMod/server-media/commit/ff0a904c9a19a3c8e2a71741d34d581419e804fa).
> The url is not a discord invite, it's for an application. So, please use the direct discord invite url.

Okay, could you please add this instead? https://discord.com/invite/Te5y5s8Njx
Or would I need a pull request for that?

**Comment by SlenkyDev** [comment]
@JakobBruening

**Pull request merged**
